AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template for TimeOff-Management Application'
# PARAMETERS
Parameters:
  GitHubOwner:
    Default: dvillarraga
    Description: The owner or organization for the GitHub project
    Type: String
  GitHubRepo:
    Default: 'timeoff-management-application'
    Description: The GitHub repository name
    Type: String
  GitHubToken:
    Default: '67d0595b0b351be11abb0e12688d24ea5340f82e'
    Description: OAuth GitHubToken
    Type: String
# RESOURCES
Resources:
  # ROLES
  CodePipeLineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
  CodeDeployIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'codedeploy.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
  InstanceIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
  # ARTIFACT AND PIPELINE 
  MyArtifactStore:
    Type: "AWS::S3::Bucket"
    Properties: 
      VersioningConfiguration:
        Status: Enabled
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: GorillaTestPipeline
      ArtifactStore:
        Location: !Ref MyArtifactStore
        Type: S3
      RoleArn: 
        Fn::GetAtt: [ CodePipeLineExecutionRole, Arn ]
      Stages:
        - Name: Source
          Actions: 
            - Name: GithubSource
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Repo: !Ref GitHubRepo
                Branch: master
                Owner: !Ref GitHubOwner
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
              - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ProjectName: !Ref ApplicationCi
              OutputArtifacts:
                - Name: BuildOutputArtifact
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CodeDeploy
              InputArtifacts:
                - Name: BuildOutputArtifact
              Configuration:
                ApplicationName: !Ref Application
                DeploymentGroupName: !Ref DeploymentGroup
              RunOrder: 1

  # CODEPIPELINE COMPONENTS
  ApplicationCi:
    Type: AWS::CodeBuild::Project
    DependsOn: CodeBuildRole
    Properties:
      Name: GorillaTestCi
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        Type: LINUX_CONTAINER
      ServiceRole: !Ref CodeBuildRole
      TimeoutInMinutes: 15
      Source:
        Type: CODEPIPELINE
  Application:
    Type: "AWS::CodeDeploy::Application"
    Properties:
      ApplicationName: GorillaTestDeployApplication
  DeploymentGroup:
    Type: "AWS::CodeDeploy::DeploymentGroup"
    Properties:
      ApplicationName: GorillaTestDeployApplication
      Ec2TagFilters:
        - Key: DeploymentGroup
          Type: KEY_AND_VALUE
          Value: !Ref AWS::StackName
      ServiceRoleArn:
        Fn::GetAtt: [ CodeDeployIAMRole, Arn ]
  # EC2 INSTANCE BY DEFAULT
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0873b46c45c11058d
      InstanceType: t2.micro
      SecurityGroups:
      - Ref: WebServerSecurityGroup
      KeyName: infragsoft
      IamInstanceProfile: !Ref MyIamInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e -u
          sudo yum update -y
          wget https://raw.githubusercontent.com/dvillarraga/timeoff-provision/master/ec2-provision/amazon-linux-2-provision.sh -O /tmp/ami-provision.sh
          sudo chmod +x /tmp/ami-provision.sh
          /tmp/ami-provision.sh install
      Tags:
        - Key: DeploymentGroup
          Value: !Ref AWS::StackName
        - Key: Name
          Value: !Ref AWS::StackName
  # EC2 Components
  MyIamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles: 
        - !Ref InstanceIAMRole
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for TimeOff-Application"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '3000'
        IpProtocol: tcp
        ToPort: '3000'
      - CidrIp: 0.0.0.0/0
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'

  
